# -*- coding: utf-8 -*-
"""Music_List

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCYZF873xa7PdlnAQxrC6uZRtIQdbd_v
"""



import openai


# Apply the API key
openai.api_key = ""


#Define a function to generate a list of songs for a particular singer using
#OpenAI GPT-3

def song_list_creation(artist_name):                      
    prompt = (f"List top 10 songs of {artist_name}")
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt=prompt,
        temperature=0,
        max_tokens=150,
        n=1,
        stop=None,
        timeout=10,
    )

    message = response.choices[0].text
    message = message.strip()
    song_list = message.split('\n')
    song_list = [song.strip() for song in song_list]
    return song_list


# Enter the artist name
artist_name = input("Please enter the name of singer: ")
# Call the function to generate the song list
song_list = song_list_creation(artist_name)


# Print the list of songs
print(f"Film songs by {artist_name}:")
for i, song in enumerate(song_list):
    print(f"{i+1}. {song}")